### ISSUE TITLE
Portuguese localization

### ISSUE THREAD

**Issue by pedro-mendonca** [Exile90/iCleaner-Localization#6]
Hi,
The current translation for portuguese is Brazilian Portuguese (pt_BR), if I add Portuguese (pt_PT) how should the files be distinguished?

Thanks

**Comment by Exile90** [comment]
Hello,
thanks a lot for willing to contribute! You can name it "Portuguese_PT.strings", I'll likely rename both the localizations when I integrate them into the app.

**Comment by pedro-mendonca** [comment]
Great!
I can't find the "daemon" strings in the main app, are they from the Pro version?
I'm trying to check everyone about readability, rendering and sometimes the context.

Thanks

**Comment by pedro-mendonca** [comment]
I have some more doubts.
1) GitHub says .strings files are binary, and it doesn't seem to show commit diffs, it's not easy to see the changes in commits, unlike regular text files. Am I using this right?
2) About the workflow, when you'll have new strings to translate, are they automatically added to language.strings files or translators have to be aware of it? Do you notify translators somehow?

**Comment by Exile90** [comment]
Some strings (including the "daemon" strings) are only used in the Pro variant of the app, yes.

.strings files cannot be diffed here because they are UTF16 encoded, and the standard git diff tool has trouble with that. You can successfully diff UTF16 files on your local fork, though it requires [some setup](http://blog.xk72.com/post/31456986659/diff-strings-files-in-git). If you'd like, I can push a suitable `.gitattributes` file to the repo, though the local config (second step in the linked post) would still be necessary on your end.

Regarding new strings, I usually email existing translators when there are new strings to be translated. By the time I do so, the new strings are already available in the [Incomplete](/Exile90/iCleaner-Localization/tree/master/Incomplete) directory of the repository.

**Comment by pedro-mendonca** [comment]
I've tryied that .gitattributes and .gitconfig with no success.
If you find it usefull to put it yourself in your repo, than I'll pull it to my fork. I'm using Git Extensions by the way.
Now I have completed the pt_PT translation and I'm pulling in a couple of minutes.

**Comment by Exile90** [comment]
I merged your pull request (commit: e0912762fae35197c51efb56a8b1b906a1cd4e6c).
Thanks again!

**Comment by pedro-mendonca** [comment]
You're welcome!
I didn't succeeded with the above setup, but my files and commitdiffs are visible in my repo. Somehow on your renaming operation it's considered as binary and diffs stopo appearing.
Maybe I'll understand it later, just keep adding strings as you're doing on the foldet "incomplete" and I'll manage it. :)
Thanks for your support.
