### ISSUE TITLE
*Refresh* button to cancel changes

### ISSUE THREAD

**Issue by pedro-mendonca** [Exile90/iCleaner-Localization#8]
On **Launch Daemons**, **Cydia Substrate Addons** and **Preference Bundles**, when one start to change the options, over the **Back** button appears the button **Refresh**. While I was using iCleaner with my recent translation pt_PT I found that the meaning of this **Refresh** wasn't correctly translated. I also think that the original english word is a bit incorrect also.
As the function of this button is to revert the recent not yet applied changes, **Refresh** is somehow confusing.
It might be more clear as **Undo**, **Revert** or **Cancel**, as the oposing option after doing some changes is **Apply**.

**Comment by Exile90** [comment]
"Refresh" makes sense if you consider what happens when you toggle switches: the state of the daemons/addons/bundles is not altered on the filesystem until the user hits "apply", meaning that tapping "refresh" actually "refreshes" the state of the switches to match the "real" state of daemons/addons/bundles.

I understand it may be confusing if you interpret it like you did, though it's a notation that's used in many similar utilities. I think "undo" would likely be more user-friendly, as it would hide this implementation detail from the user, though if you think about it it's not 100% correct: you're not undoing any change, since no change has been applied to the underlying filesystem.

I'll consider this suggestion in the future, whenever a major localization rewrite needs to take place. Applying it right now would invalidate many complete translations, which is something I tend to avoid unless strictly necessary.

**Comment by pedro-mendonca** [comment]
Thanks, feel free to close the issue, as this is more a suggestion than a real issue or bug.
